# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbff34993a5c59d25215a703f51f849d9358fbd023d83850e57ad19b60d0e4416c150693ea56588b5244270c6197f6ebf1ef425faf4e3aaec68feb90a718e50e
  config_aws_access_key_id: <%= ENV["S3_KEY"] %>
  config_aws_secret_access_key: <%= ENV["S3_SECRET"] %>


test:
  secret_key_base: b0492f89731a2015de0be556e5e67ea4f95bfd510bca74630987ad199153e21365c7f4489cfa6b0e3f7eb8eba5acd836aec0ad499bff6b407460c80ae52520d0
  config_aws_access_key_id: <%= ENV["S3_KEY"] %>
  config_aws_secret_access_key: <%= ENV["S3_SECRET"] %>


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  config_aws_access_key_id: <%= ENV["S3_KEY"] %>
  config_aws_secret_access_key: <%= ENV["S3_SECRET"] %>
